### ISSUE TITLE
RuntimeError: Model class menus.models.CacheKey doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by agusmakmun** [mishbahr/djangocms-instagram#5]
Hello there, we try this djangocms-instagram under `Django==1.9.5`, and we getting the error like this. 
Thanks so much before..

``` shell
(instagram-env) official ~$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/djangocms_instagram/models.py", line 6, in <module>
    from cms.models import CMSPlugin
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/cms/models/__init__.py", line 3, in <module>
    from .pagemodel import *  # nopyflakes
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/cms/models/pagemodel.py", line 27, in <module>
    from menus.menu_pool import menu_pool
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/menus/menu_pool.py", line 19, in <module>
    from menus.models import CacheKey
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/menus/models.py", line 30, in <module>
    class CacheKey(models.Model):
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class menus.models.CacheKey doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

**Comment by mishbahr** [comment]
Hey @agusmakmun,

What version of `django-cms` are you running?

Please can you check 'menus' are in your `INSTALLED_APPS`.

e.g.

```
INSTALLED_APPS = (      
    'cms',
    'treebeard', 
    'menus',  # helper for model independent hierarchical website navigation
    'sekizai', 
    'djangocms_admin_style',
    'django.contrib.admin'.
    'django.contrib.messages',
)
```

**Comment by agusmakmun** [comment]
now we using `django-cms==3.2.3`, ok thankyou sir..

**Comment by mishbahr** [comment]
@agusmakmun have you resolved your problem? Can I close this issue?

**Comment by agusmakmun** [comment]
yap, thanks sir.. :+1:

**Comment by agusmakmun** [comment]
how about this sir? we found this error when we migrate..

```
ValueError: ModelState.fields cannot refer to a model class - "account.to" does. Use a string reference instead.
```

**Comment by mishbahr** [comment]
Hello again.
@agusmakmun Please can you provide full traceback?

From what I can tell, its an issue with another library `django-connected`
Please install the latest version from github https://github.com/mishbahr/django-connected 

```
pip install -e git+https://github.com/mishbahr/django-connected.git#egg=django-connected
```

**Comment by agusmakmun** [comment]
thank you so much sir.. :+1:  now we have done with this:

```
pip install -e git+https://github.com/mishbahr/django-connected.git#egg=django-connected
```

this my traceback before:

``` shell
(instagram-env) official ~$ ./manage.py migrate
/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/connected_accounts/admin.py:91: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^(.+)/json/$', wrap(self.json_view), name='%s_%s_json' % info),

/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/djangocms_instagram/cms_plugins.py:84: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='%s_%s_users_search' % info),

Operations to perform:
  Apply all migrations: djangocms_instagram, sessions, admin, sites, auth, menus, contenttypes, connected_accounts, cms
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 183, in handle
    executor.loader.project_state(),
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 338, in project_state
    return self.graph.make_state(nodes=nodes, at_end=at_end, real_apps=list(self.unmigrated_apps))
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/db/migrations/graph.py", line 280, in make_state
    project_state = self.nodes[node].mutate_state(project_state, preserve=False)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 88, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 53, in state_forwards
    list(self.managers),
  File "/home/agaust/ENV/instagram-env/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 367, in __init__
    'Use a string reference instead.' % name
ValueError: ModelState.fields cannot refer to a model class - "account.to" does. Use a string reference instead.
```

---

btw, how i can implement such as **Location Search**?
In my test, i just extending from template `admin/djangocms_instagram/search.html` inside the `views.py`, but we have nothing.. I also need a library from [djangocms-gmaps](https://github.com/mishbahr/djangocms-gmaps) or how i can do it ?

![nothing](https://cloud.githubusercontent.com/assets/7134451/14578832/64ba983a-03be-11e6-8d72-de60a674e0c2.png)
